# Generated by Django 2.0.7 on 2018-07-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0006_auto_20180704_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='tweet_id',
        ),
        migrations.AddField(
            model_name='tweet',
            name='tweet',
            field=models.ManyToManyField(blank=True, related_name='_tweet_tweet_+', to='tweets.Tweet'),
        ),
    ]
