# Generated by Django 2.0.7 on 2018-07-04 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0007_auto_20180704_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='ids',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='twits', to='tweets.Tweet'),
        ),
    ]
