# Generated by Django 2.0.7 on 2018-07-04 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0008_tweet_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='tweet',
        ),
    ]
